In [1]:
import numpy as np

In [2]:
inp_data = np.array([[0,0],[0,1],[1,0],[1,1]])
out_data_AND = np.array([0,0,0,1])

In [3]:
step_function_AND = lambda x:1 if x>=1.5 else 0

In [4]:
pred_AND = np.array(list(map(lambda i:step_function_AND(np.sum(i)),inp_data)))
pred_AND

array([0, 0, 0, 1])

In [5]:
inp_data = np.array([[0,0],[0,1],[1,0],[1,1]])
out_data_OR = np.array([0,1,1,1])

In [6]:
step_function_OR = lambda x:1 if x>=0.5 else 0

In [7]:
pred_OR = np.array(list(map(lambda i:step_function_OR(np.sum(i)),inp_data)))
pred_OR

array([0, 1, 1, 1])

In [8]:
class Perceptron:
    def __init__(self,inp_dim,lr,epochs):
        self.lr=lr
        self.epochs=epochs
        self.weights=np.random.rand(inp_dim)
        self.bias=np.random.rand()
    def step_function(self,x):
        return 1 if x>=27 else 0
    def predict(self,input):
        weighted_sum=np.dot(input,self.weights)+self.bias
        out=self.step_function(weighted_sum)
        return out
    def fit(self,inp,out):
        for i in range(self.epochs):
            for j in range(len(inp)):
                y_pred=self.predict(inp[j])
                error=out[j]-y_pred
                self.weights+=(self.lr*error*inp[j])
                self.bias+=(self.lr*error)

In [9]:
inp_data = np.array([[0,0],[0,1],[1,0],[1,1]])
out_AND = np.array([0,0,0,1])

In [11]:
perceptron_AND=Perceptron(inp_dim=2,epochs=500,lr=0.1)

In [14]:
perceptron_AND.fit(inp_data,out_AND)
for i in inp_data:
    print(f"{i}:---{perceptron_AND.predict(i)}")

[0 0]:---0
[0 1]:---0
[1 0]:---0
[1 1]:---1


In [15]:
inp_data = np.array([[0,0],[0,1],[1,0],[1,1]])
out_OR = np.array([0,1,1,1])

In [16]:
perceptron_OR=Perceptron(inp_dim=2,epochs=500,lr=0.1)

In [17]:
perceptron_OR.fit(inp_data,out_OR)
for i in inp_data:
    print(f"{i}:---{perceptron_OR.predict(i)}")

[0 0]:---0
[0 1]:---1
[1 0]:---1
[1 1]:---1


In [18]:
perceptron_AND.weights

array([9.47104073, 9.04175912])

In [19]:
perceptron_AND.bias

8.630053736933311

In [20]:
perceptron_OR.weights

array([10.66230903, 10.52567743])

In [21]:
perceptron_OR.bias

16.59871565078408

In [22]:
inp_data = np.array([[0,0],[0,1],[1,0],[1,1]])
out_XOR = np.array([0,1,1,0])

In [23]:
perceptron_XOR=Perceptron(inp_dim=2,lr=0.3,epochs=500)

In [24]:
perceptron_XOR.fit(inp_data,out_XOR)
for i in inp_data:
    print(f"{i}:---perceptron_XOR.predict{i}")


[0 0]:---perceptron_XOR.predict[0 0]
[0 1]:---perceptron_XOR.predict[0 1]
[1 0]:---perceptron_XOR.predict[1 0]
[1 1]:---perceptron_XOR.predict[1 1]
