In [50]:
import numpy as np

In [51]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sig_der(x):
    return x * (1-x)

In [52]:
inp_data = np.array([[0,0],[0,1],[1,0],[1,1]])
out_XOR = np.array([[0],[1],[1],[0]])

In [53]:
inp_data,out_XOR

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [54]:
inp_neuron=2
hid_neuron=6
out_neuron=1

In [55]:
inp_hid_wt = 2*np.random.random((inp_neuron,hid_neuron))-1

In [56]:
inp_hid_wt

array([[ 0.72961618,  0.13664805,  0.072002  , -0.42277018,  0.28526605,
        -0.2547287 ],
       [ 0.88330391, -0.27470026,  0.76922909, -0.74686503,  0.64237791,
        -0.83269897]])

In [57]:
hid_out_wt = 2*np.random.random((hid_neuron,out_neuron))-1

In [58]:
hid_out_wt

array([[-0.15921027],
       [-0.94264972],
       [ 0.36813058],
       [-0.30077963],
       [ 0.77652756],
       [-0.99348231]])

In [59]:
epochs = 1000
lr=0.5

In [60]:
for i in range(epochs):
    # feed forward
    
    hid_layer_out=sigmoid(np.dot(inp_data,inp_hid_wt))
    out_layer_out=sigmoid(np.dot(hid_layer_out,hid_out_wt))

    # output layer error
    error = out_XOR-out_layer_out
    
    # back propogation
    
    delta_output=error*sig_der(out_layer_out)
    new_hid_out_wt=lr*np.dot(hid_layer_out.T,delta_output)

    #hidden layer error
    
    hidden_error=np.dot(delta_output,hid_out_wt.T)
    delta_hidden=hidden_error*sig_der(hid_layer_out)
    new_inp_hid_wt=lr*np.dot(inp_data.T,delta_hidden)
    
    # changing weights
    hid_out_wt+=new_hid_out_wt
    inp_hid_wt+=new_inp_hid_wt
    

In [61]:
hidden_layer_output=sigmoid(np.dot(inp_data,inp_hid_wt))
final_output=sigmoid(np.dot(hidden_layer_output,hid_out_wt))

In [62]:
np.round(final_output)

array([[0.],
       [1.],
       [1.],
       [0.]])